# Generated by Django 5.0.4 on 2024-12-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avion', models.CharField(editable=False, max_length=4)),
                ('date_mise_service', models.DateField(auto_now_add=True)),
                ('heures_vol_der_rev', models.PositiveIntegerField(default=0)),
                ('heures_vol', models.PositiveIntegerField(default=0)),
                ('date_der_rev', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_navigant', models.BooleanField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_embauche', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LU', 'lundi'), ('MA', 'mardi'), ('ME', 'mercredi'), ('JE', 'jeudi'), ('VE', 'vendredi'), ('SA', 'samedi'), ('DI', 'dimanche')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nom_pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeNavigant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_vol', models.PositiveIntegerField(default=0)),
                ('heures_mois_vol', models.PositiveIntegerField(default=0)),
                ('avions', models.ManyToManyField(related_name='equipe', to='myapp.avion')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigant', to='myapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('heures_vol', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='myapp.avion')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('duree', models.DurationField()),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_vols', to='myapp.ville')),
                ('avion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols', to='myapp.avion')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_vols', to='myapp.ville')),
                ('jours', models.ManyToManyField(related_name='vols', to='myapp.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrive', models.TimeField()),
                ('duree', models.DurationField()),
                ('no_ord', models.PositiveIntegerField(default=0)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escales', to='myapp.ville')),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escales', to='myapp.vol')),
            ],
        ),
    ]
