# Generated by Django 5.1.4 on 2024-12-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employenavigant',
            name='avions',
            field=models.ManyToManyField(blank=True, related_name='equipe', to='myapp.avion'),
        ),
        migrations.AlterField(
            model_name='employenavigant',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='navigant', serialize=False, to='myapp.employe'),
        ),
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('nom', 'nom_pays'), name='unique_city_country'),
        ),
    ]
