# Generated by Django 5.0.4 on 2024-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_avion_employe_jour_ville_employenavigant_rapport_vol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='date_der_rev',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='type_avion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jour',
            name='jour',
            field=models.CharField(choices=[('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi'), ('SA', 'Samedi'), ('DI', 'Dimanche')], max_length=2, unique=True),
        ),
    ]
