# Generated by Django 5.1.4 on 2024-12-24 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employenavigant_avions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[\\d\\s+\\-]+$')]),
        ),
    ]
