# Generated by Django 5.0.4 on 2024-12-19 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_avion_date_der_rev_alter_avion_type_avion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escale',
            options={'ordering': ['no_ord']},
        ),
        migrations.AlterField(
            model_name='escale',
            name='no_ord',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
