# Generated by Django 5.1.4 on 2024-12-27 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_avion_est_interdit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='adresse',
            field=models.TextField(default='hay hassani'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avion',
            name='date_mise_service',
            field=models.DateField(auto_now_add=True, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(auto_now_add=True, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='escale',
            name='duree',
            field=models.DurationField(help_text='Format: D HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='escale',
            name='heure_arrive',
            field=models.TimeField(help_text='Format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='jour',
            name='jour',
            field=models.CharField(choices=[('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi'), ('SA', 'Samedi'), ('DI', 'Dimanche')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 27, 2, 58, 41, 90599, tzinfo=datetime.timezone.utc), help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='duree',
            field=models.DurationField(help_text='Format: D HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='heure_depart',
            field=models.TimeField(help_text='Format: HH:MM:SS'),
        ),
    ]
