# Generated by Django 5.0.4 on 2024-12-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_escale_unique_escale_per_vol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avion',
            old_name='type_avion',
            new_name='type',
        ),
    ]
